version: '3.7'
services:
    redis:
        image: redis
        restart: always
        ports:
            - 6379:6379
        networks: 
            - gydam-network
    utils:
        build: ./gydam-utils
        volumes: 
            - utils:/usr/gydam-utils/
    postgres:
        image: postgres
        environment: 
            POSTGRES_PASSWORD: 'gydam'
            POSTGRES_USER: 'gydam'
        ports:
            - 5432:5432
        networks:
            - gydam-network
        volumes:
            - postgres:/var/lib/postgresql/data
    db:
        build: ./gydam-db
        volumes: 
            - db:/usr/gydam-db/
        depends_on: 
            - utils
            - postgres
            - redis
        environment: 
            DB_HOST: postgres
        networks:
            - gydam-network
        command: npm run setup -- -y
    agent:
        build: ./gydam-agent
        depends_on: 
            - db
        networks: 
            - gydam-network
        volumes: 
            - agent:/usr/gydam-agent/
            - utils:/usr/gydam-utils/
    mqtt:
        build: ./gydam-mqtt
        depends_on: 
            - agent
        environment: 
            REDIS_HOST: redis
            DB_HOST: postgres
        networks:
            - gydam-network
        ports:
            - 1883:1883
            - 3000:3000
            - 4000:4000
            - 8883:8883
        volumes: 
            - db:/usr/gydam-db/
            - utils:/usr/gydam-utils/
    
networks: 
    gydam-network:
        driver: bridge

volumes:
    agent:
    utils:
    db:
    postgres:
